#!/bin/bash

bspc monitor -d 一 二 三 四 五 六 七 八

bspc config border_width         4
bspc config focused_border_color "#6C6F93"
bspc config normal_border_color "#282e3a"

#ln -s $WALLPAPERS/nord-theme $HOME/.config/GIMP/2.10/splashes

#$HOME/.config/bspwm/bspborders &
$HOME/.scripts/autostart.bspwm
