#!/usr/bin/env bash

source $HOME/.scripts/colors

#c_out="0x323d43"
#c_focused="0xa7c080"
#c_unfocused="0x3c474d"

c_out="0x323d43"
c_focused="0xa7c080"
c_unfocused="0x3c474d"

unfocus() {
	for wid in $(lsw | sed "/$(pfw)/d"); do
		chwb2 -I $c_unfocused -O $c_out -i 2 -o 8 $wid
	done
}

tempprint() {
  echo "event: $1"
  echo "wid: $2"
}

# read all focus events from bspwm
bspc subscribe node_geometry node_focus | while read var; do
#  event=$(echo "$var" | awk '{print $1}')
#  echo "event: $event"
  # focus colors on focused window
  chwb2 -i 2 -o 8 -I $c_focused -O $c_out $(pfw)
  unfocus
  
done


