#!/bin/bash

initial_workspace=`qdbus org.kde.KWin /KWin currentDesktop`
goal_workspace=$1
launch_application=$2
sleeptime=2
if [ $# -eq 3 ] 
then 
    sleeptime=$3
fi

qdbus org.kde.KWin /KWin setCurrentDesktop "$goal_workspace" &
exec ${launch_application} &
sleep $sleeptime
qdbus org.kde.KWin /KWin setCurrentDesktop "$initial_workspace"
exit
