#!/bin/bash
bspc monitor -d    ﳁ   ﭮ  

bspc config focused_border_color "#E9E9E9"
bspc config normal_border_color "#0F1212"
bspc config border_width         5

killall bspborders
 
$HOME/.scripts/autostart.bspwm
