#!/bin/bash

bspc monitor -d TERM WEB CODE MISC EDIT CHAT DISCORD MUSIC


bspc config border_width         2
bspc config focused_border_color "#6C6F93"
bspc config normal_border_color "#282e3a"

#ln -s $WALLPAPERS/nord-theme $HOME/.config/GIMP/2.10/splashes

#$HOME/.config/bspwm/bspborders &
#$HOME/.scripts/autostart.bspwm
