#!/bin/bash

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config focused_border_color "#daa6ca"
bspc config normal_border_color "#282e3a"

mkdir -p $HOME/.config/GIMP/2.10/splashes &> /dev/null
ln -s $WALLPAPERS/nord-theme $HOME/.config/GIMP/2.10/splashes

$HOME/.scripts/autostart.bspwm
