#!/usr/bin/env bash
source $HOME/.scripts/colors

c_out="0x2e3440"
c_focused="0xdaa6ca"
c_unfocused="0x282e3a"

unfocus() {
	for wid in $(lsw | sed "/$(pfw)/d"); do
		chwb2 -I $c_unfocused -O $c_out -i 4 -o 4 $wid
	done
}

tempprint() {
  echo "event: $1"
  echo "wid: $2"
}

# read all focus events from bspwm
bspc subscribe node_geometry node_focus | while read var; do
#  event=$(echo "$var" | awk '{print $1}')
#  echo "event: $event"
  # focus colors on focused window
  chwb2 -i 4 -o 4 -I $c_focused -O $c_out $(pfw)
  unfocus
  
done

