#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

$HOME/.scripts/custom-autostart

#nm-applet &
xsetroot -cursor_name left_ptr
sxhkd &
picom --experimental-backends &
nitrogen --restore
wmname LG3D &
lxpolkit &
xset -dpms s off & # disable screen blanking
dropbox &
dunst &
nautilus --gapplication-service &

# Swallow

#nohup pidof $HOME/.scripts/bspswallow || $HOME/.scripts/bspswallow &
pgrep bspswallow || nohup ~/.scripts/bspswallow &

# Workspaces

bspc config window_gap          20
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
$HOME/.config/bspwm/autostart

# Default state/workspace for applications
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a nomacs state=floating
bspc rule -a nomacs state=floating
bspc rule -a "Image Lounge" state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config pointer_modifier mod4

#sleep 0.69

# Autostart applications:

# Start Polybar
$HOME/.config/polybar/scripts/restart-polybar.sh &

# Start floating kitty terminal
bspc rule -a \* -o state=floating && sleep 0.015 ; kitty -e $SHELL -c "$HOME/.config/neofetch/launch-neofetch.sh && $SHELL" &

sleep 1.55 

# Start firefox
/bin/bash -c "bspc desktop -f '^2' --follow ; bspc rule -a \* -o node=@$(bspc query -D -d):.focused split_dir=south follow=off ; firefox file:///home/$USER/.config/startpage/index.html &" &
bspc desktop -f '^2' --follow &

