#!/bin/bash

dir=$1

#SECONDS OF COOLDOWN
COOLDOWN=120

# Dictionary
[ $dir = 'nord' ] && dir='/home/zodd/Pictures/Wallpapers/Wallpapers/nord-theme'
[ $dir = 'vaporwave' ] && dir='/home/zodd/Pictures/Wallpapers/Wallpapers/vaporwave-theme'
[ $dir = 'gruvbox' ] && dir='/home/zodd/Pictures/Wallpapers/Wallpapers/gruvbox-theme'
[ $dir = 'doom' ] && dir='/home/zodd/Pictures/Wallpapers/Wallpapers/doom-theme'
# --- </> ---

# Error check
[ ! -d $dir ] && echo "Directory $dir does not exist" && exit 1

# Just one iteration
[ $2 = 'next' ] && feh --randomize --bg-fill $dir && exit 0      

while : 
do
    feh --randomize --bg-fill $dir
    sleep $COOLDOWN
done
