#!/bin/bash

if [[ $* == *--update* || $* == -*u* ]];
then
    echo
    echo "updating dotfiles global configuration..."
    echo

    # fish
    [ -d $DOTFILES/global-config/.config/fish ] || mkdir -p $DOTFILES/global-config/.config/fish
    cp $HOME/.config/fish/config.fish $HOME/.config/fish/fish_variables $DOTFILES/global-config/.config/fish

    # zsh
    cp -r $HOME/.zshrc $HOME/.oh-my-zsh $DOTFILES/global-config &> /dev/null

    # kitty
    cp -r $HOME/.config/kitty/kitty.conf $DOTFILES/global-config/.config/kitty

    # neofetch
    [ -d $DOTFILES/global-config/.config/neofetch ] || mkdir -p $DOTFILES/global-config/.config/neofetch
    cp -r $HOME/.config/neofetch/config.conf $DOTFILES/global-config/.config/neofetch

    # nvim
    cp -r $HOME/.config/nvim $DOTFILES/global-config/.config &> /dev/null
    rm $DOTFILES/global-config/.config/nvim/colorscheme.vim

    # browser startpage
    cp $HOME/.config/startpage/index.html $HOME/.config/startpage/script.js $DOTFILES/global-config/.config/startpage
    [ -d $DOTFILES/global-config/.config/startpage/resources ] || mkdir -p $DOTFILES/global-config/.config/startpage/resources

    # bspwm
    [ -d $DOTFILES/global-config/.config/bspwm ] || mkdir -p $DOTFILES/global-config/.config/bspwm
    cp $HOME/.config/bspwm/bspwmrc $HOME/.config/bspwm/noswallow $HOME/.config/bspwm/terminals $DOTFILES/global-config/.config/bspwm

    # sxhkd
    cp -r $HOME/.config/sxhkd $DOTFILES/global-config/.config

    # ranger
    cp -r $HOME/.config/ranger $DOTFILES/global-config/.config &> /dev/null

    # thunar
    cp $HOME/.config/thunar $DOTFILES/global-config/.config
    
    # ~/.scripts
    cp -r $HOME/.scripts $DOTFILES

    # polybar scripts
    cp -r $HOME/.config/polybar/scripts $HOME/.config/polybar/fonts $HOME/.config/polybar/modules $DOTFILES/global-config/.config/polybar

    # .bashrc
    cp $HOME/.bashrc $DOTFILES/global-config
    cp $HOME/.zprofile $DOTFILES/global-config
    cp $HOME/.xinitrc $DOTFILES/global-config

    # Additional flags
    [[ $* == *--fonts* || $* == -*f* ]] && echo "copying fonts..." && cp -r $HOME/.fonts/ $DOTFILES
    [[ $* == *--themes* || $* == -*t* ]] && echo "copying themes..." && cp -r $HOME/.themes/ $DOTFILES
    [[ $* == *--icons* || $* == -*i* ]] && echo "copying icons..." && cp -r $HOME/.icons/ $DOTFILES
    [[ $* == *--wallpapers* || $* == -*w* ]] && echo "copying wallpapers..." && cp -r $HOME/Pictures/Wallpapers/Wallpapers $DOTFILES

    echo
    
    figlet "done !"

    exit
fi

# ------------------- SPECIFIC THEME -------------------

theme_name=$1

echo [INFO]: preparing $theme_name theme configuration ...
echo with dotfiles in $DOTFILES ...

theme_dir="$DOTFILES/themes/${theme_name}"

if [ -d $theme_dir ];
then
    echo -n "Theme $theme_name already exists, do you want to override its entire configuration? (y/N) " && read REPLY
    
    shopt -s nocasematch
    case "$REPLY" in
     "y" ) echo "[INFO]: overriding configuration ...";;
     *) exit ;;
    esac
fi

[ ! -d $theme_dir ] && mkdir -p $theme_dir && echo [INFO]: created theme directory in $theme_dir

theme_config="$theme_dir/.config"
[ ! -d $theme_config ] && mkdir $theme_config && echo [INFO]: created .config directory in $theme_dir

# $HOME/.config
echo [INFO]: copying $HOME/.config to $theme_config ...

mkdir $theme_config/discord

cp -r $HOME/.config/compton.conf $theme_config

cp -r $HOME/.config/nitrogen $theme_config

mkdir -p $theme_config/kitty
cp -r $HOME/.config/kitty/colorscheme.conf $theme_config/kitty

mkdir -p $theme_config/bspwm
cp -r $HOME/.config/bspwm/bspborders $HOME/.config/bspwm/autostart $theme_config/bspwm

mkdir -p $theme_config/nvim
cp -r $HOME/.config/nvim/colorscheme.vim $theme_config/nvim

cp -r $HOME/.config/Thunar $theme_config

dconf dump /org/gnome/gedit/ > $theme_config/gedit-dump.dconf

mkdir -p $theme_config/rofi
cp -r $HOME/.config/rofi/config.rasi $theme_config/rofi

mkdir $theme_config/polybar
cp -r $HOME/.config/polybar/config.bpswm $HOME/.config/polybar/config.openbox $theme_config/polybar

cp -r $HOME/.config/dunst $theme_config
cp -r $HOME/.config/discord/themes $theme_config/discord

mkdir $theme_config/spicetify
cp -r $HOME/.config/spicetify/Extracted $HOME/.config/spicetify/config.ini $theme_config/spicetify

cp -r $HOME/.config/gtk-3.0 $theme_config
cp -r $HOME/.config/gtk-2.0 $theme_config
cp -r $HOME/.config/.gtkrc-2.0 ../$theme_config

echo
echo [INFO]: finished copying config files
echo

figlet "done !"

