#!/bin/bash

project_name=$1
project_dir=$2

# Check if $2 exists, else it will create the project in the current directory ($PWD)
[ -z $project_dir ] && project_dir=$PWD 

cd $project_dir

# Checks for a project with same name in the directory
[ -d $project_name ] && echo \[ERROR\]: Project \'$project_name\' already exists in directory: \'$project_dir\' && exit 1

git clone https://github.com/zodd18/MVC-Template.git $project_name && rm -rf ./$project_name/.git/
