#!/bin/bash

theme_name=$1

echo [INFO]: updating $theme_name rice ...

theme_dir="$DOTFILES/themes/${theme_name}"

[ ! -d $theme_dir ] && echo [ERROR]: theme: \'$theme_dir\' not found && exit 1

cd $theme_dir

new=0
[ ! -d .git ] && new=1
[ ! -d .git ] && git init && git remote add origin "https://github.com/zodd18/$theme_name"

git add * 
#git add ./.* 
git add ./.
git commit -m "Minor changes"
git push

if [[ $new -eq 1 || $* == *--submodule* || $* == -*submodule* ]];
then
    cd $DOTFILES
    git rm -r --cached ./themes/$theme_name
    git submodule add https://github.com/zodd18/$theme_name.git ./themes/$theme_name
fi

upload-dotfiles
