#!/bin/bash
bspc monitor -d    ﳁ   ﭮ  

bspc config focused_border_color "#928374"
bspc config normal_border_color "#282828"

mkdir -p $HOME/.config/GIMP/2.10/splashes &> /dev/null
ln -s $WALLPAPERS/gruvbox-theme $HOME/.config/GIMP/2.10/splashes

$HOME/.scripts/autostart.bspwm
