#! /bin/sh

sxhkd &
#nm-applet &
compton &
feh --bg-fill $HOME/Pictures/Wallpapers/Wallpapers/gruvbox-theme/frog_gruvbox_hard.png &
polybar example &
wmname LG3D &
lxpolkit &
xset -dpms s off & # disable screen blanking &
dropbox &
dunst &

# Swallow

pidof $HOME/.scripts/bspswallow || $HOME/.scripts/bspswallow &

# Workspaces

bspc monitor -d    ﳁ    

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color "#d79921"
bspc config normal_border_color "#a89984"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config pointer_modifier mod4

# Autostart applications:
alacritty -e /bin/fish -C neofetch &
sleep 0.15 && bspc rule -a \* -o desktop='^2' && sleep 0.85 && firefox &
